### ISSUE TITLE
The grabber bot (BumbleBee) should support gzip

### ISSUE THREAD

**Issue by FO-nTTaX** [WikiApiary/wikibees#20]
If your bot would support gzip, we would appreciate that. I created a pull request here https://github.com/WikiApiary/wikibees/pull/19 for you to use as you please.

Tagging @hexmode based on a suggestion by Kghbln ( https://www.wikiapiary.com/wiki/User_talk:Kghbln#Can_the_bot_be_made_to_accept_Gzip.3F )

**Comment by kghbln** [comment]
The pull https://github.com/WikiApiary/wikibees/pull/19 got merged. I guess the data should start to move in now.
