### ISSUE TITLE
Bees constantly erroring

### ISSUE THREAD

**Issue by Adrthegamedev** [WikiApiary/wikibees#27]
In the bot log, Bumble Bee is constantly responding with "No sites to process for segment #" (with a website link of [...connecting...](https://wikiapiary.com/w/index.php?title=...connecting...&action=edit&redlink=1)), and Audit Bee also constantly erroring with "Unhandled exception No option 'user-agent' in section: 'Audit Bee'.", with the last two audit bee errors being on [Kingdom Hearts Wiki](https://wikiapiary.com/wiki/Kingdom_Hearts_Wiki) and [Garriki](https://wikiapiary.com/wiki/Garriki) for some reason, instead of what the rest show, [Error](https://wikiapiary.com/w/index.php?title=Error&action=edit&redlink=1).

This might have been started by the recent commits to this repository, as before those everything seemed to be perfectly fine.

**Comment by Adrthegamedev** [comment]
Update: Instead of Audit Bee erroring on Garriki now, Audit Bee errors with "Unhandled exception unsupported operand type(s) for +: 'NoneType' and 'str'.".

**Comment by hexmode** [comment]
Part of the issue was a .cfg file that wasn't set up correctly with User-Agent setting.  That should be fixed now.

**Comment by hexmode** [comment]
It looks like the updating is happening now.
