### ISSUE TITLE
Issue logs not renderd correctly

### ISSUE THREAD

**Issue by kghbln** [WikiApiary/wikibees#6]
Sometimes in case the issue logged includes a link it cannot be rendered correctly on wiki since apostrophes are now wrapped around the link. See [Wikia Developers Wiki](https://wikiapiary.com/wiki/Wikia_Developers_Wiki) as an example.

```
['http://dev.wikia.com/api.php?action=query&meta=siteinfo&siprop=libraries&format=json' link]
```

**Comment by hexmode** [comment]
I fixed the links on [ https://wikiapiary.com/wiki/WikiApiary:Website_logs | the log files ] [ https://wikiapiary.com/w/index.php?title=WikiApiary%3AWebsite_logs&type=revision&diff=3052605&oldid=3048791 | by using a template ] . Used [ https://wikiapiary.com/wiki/Template:Website_display_log_row | a template ] [ https://wikiapiary.com/w/index.php?title=Template%3AWebsite&type=revision&diff=3079923&oldid=2621090 | here ] and it looks like this is fixed.

**Comment by kghbln** [comment]
I should be now. Great an thanks!
