### ISSUE TITLE
AuditBee / Integer overflow?

### ISSUE THREAD

**Issue by kghbln** [WikiApiary/wikibees#9]
Reported [on wiki](https://wikiapiary.com/wiki/WikiApiary_talk:Total_pages) and can bee [seen here](https://wikiapiary.com/w/index.php?diff=3282138).

**Comment by kghbln** [comment]
The [Wikipan-API](https://wikiapiary.com/wiki/Wikipan) was emitting bogus so I deactivated the website and switched to another counting system not involving AuditBee: [diff](https://wikiapiary.com/w/index.php?title=Main_Page&type=revision&diff=3692359&oldid=2601311)

**Comment by MvGulik** [comment]
Please re-open, this problem is still there.
